#ifndef _ADAPTER_H_INCLUDED_
#define _ADAPTER_H_INCLUDED_

typedef enum
{
    ADAPTER_UDB_13_FLEX,
    ADAPTER_JOKER_FLEX,
    ADAPTER_UDB_6_FLEX,
    ADAPTER_UDB_17_FLEX,
    ADAPTER_UDB_12_FLEX,
    ADAPTER_UNKNOWN
} adapter_type_t;

#define ADAPTER_UDB_13_FLEX_ADC_MIN     (54000)
#define ADAPTER_JOKER_FLEX_ADC_MIN      (51000)
#define ADAPTER_UDB_6_FLEX_ADC_MIN      (47000)
#define ADAPTER_UDB_17_FLEX_ADC_MIN     (44000)
#define ADAPTER_UDB_12_FLEX_ADC_MIN     (40000)

#endif
